export const fakeTable = [
  {
    GREEN: "",
    PINK: "1",
    V_YOMAN_BIKUR_BIKUR_ACHARON_0: "27/11/2022",
    V_YOMAN_BIKUR_DIRA_0: "016",
    V_YOMAN_BIKUR_KNISA_0: "1",
    V_YOMAN_BIKUR_KOMA_0: "04",
    V_YOMAN_BIKUR_MIS_BAIT_0: "9",
    V_YOMAN_BIKUR_MIS_ZIHUY_0: "023607377",
    V_YOMAN_BIKUR_MIVNE_0: "1063",
    V_YOMAN_BIKUR_SHAAT_BIKUR_0: "16:00",
    V_YOMAN_BIKUR_SHEM_0: "אלישע רחל",
    V_YOMAN_BIKUR_SHEM_ISHUV_0: "יבנה",
    V_YOMAN_BIKUR_SHEM_RECHOV_0: "חרמון",
    V_YOMAN_BIKUR_SHIKUN_0: "2240",
    V_YOMAN_BIKUR_TARICH_BIKUR_0: "27/11/2022",
  },
  {
    GREEN: "",
    PINK: "1",
    V_YOMAN_BIKUR_BIKUR_ACHARON_0: "03/08/2022",
    V_YOMAN_BIKUR_DIRA_0: "013",
    V_YOMAN_BIKUR_KNISA_0: "1",
    V_YOMAN_BIKUR_KOMA_0: "01",
    V_YOMAN_BIKUR_MIS_BAIT_0: "2",
    V_YOMAN_BIKUR_MIS_ZIHUY_0: "054210588",
    V_YOMAN_BIKUR_MIVNE_0: "0042",
    V_YOMAN_BIKUR_SHAAT_BIKUR_0: "",
    V_YOMAN_BIKUR_SHEM_0: "כהן חיים",
    V_YOMAN_BIKUR_SHEM_ISHUV_0: "חולון",
    V_YOMAN_BIKUR_SHEM_RECHOV_0: "הכנסת",
    V_YOMAN_BIKUR_SHIKUN_0: "2015",
    V_YOMAN_BIKUR_TARICH_BIKUR_0: "",
  },
  {
    GREEN: "",
    PINK: "1",
    V_YOMAN_BIKUR_BIKUR_ACHARON_0: "03/08/2022",
    V_YOMAN_BIKUR_DIRA_0: "012",
    V_YOMAN_BIKUR_KNISA_0: "ב",
    V_YOMAN_BIKUR_KOMA_0: "03",
    V_YOMAN_BIKUR_MIS_BAIT_0: "7",
    V_YOMAN_BIKUR_MIS_ZIHUY_0: "062186168",
    V_YOMAN_BIKUR_MIVNE_0: "0007",
    V_YOMAN_BIKUR_SHAAT_BIKUR_0: "",
    V_YOMAN_BIKUR_SHEM_0: "בוזגלו יוסף",
    V_YOMAN_BIKUR_SHEM_ISHUV_0: "חולון",
    V_YOMAN_BIKUR_SHEM_RECHOV_0: "שד קוגל",
    V_YOMAN_BIKUR_SHIKUN_0: "2040",
    V_YOMAN_BIKUR_TARICH_BIKUR_0: "",
  },
  {
    GREEN: "",
    PINK: "1",
    V_YOMAN_BIKUR_BIKUR_ACHARON_0: "03/08/2022",
    V_YOMAN_BIKUR_DIRA_0: "001",
    V_YOMAN_BIKUR_KNISA_0: "א",
    V_YOMAN_BIKUR_KOMA_0: "01",
    V_YOMAN_BIKUR_MIS_BAIT_0: "8",
    V_YOMAN_BIKUR_MIS_ZIHUY_0: "051928919",
    V_YOMAN_BIKUR_MIVNE_0: "0008",
    V_YOMAN_BIKUR_SHAAT_BIKUR_0: "",
    V_YOMAN_BIKUR_SHEM_0: "גדליה מרגוט",
    V_YOMAN_BIKUR_SHEM_ISHUV_0: "חולון",
    V_YOMAN_BIKUR_SHEM_RECHOV_0: "שד קוגל",
    V_YOMAN_BIKUR_SHIKUN_0: "2040",
    V_YOMAN_BIKUR_TARICH_BIKUR_0: "",
  },
];

export const tenant_1 = [
  {
    CHIMUMMAYIM: "דוד שמש דירתי",
    CHADARBITACHON: "מקלט תת קרקעי לבניין",
    SHETACH: "52",
    CHADARIM: "2",
    CATZAEICHADARIM: "",
    MADREGOT: "",
    TAR_BIKUR: "",
    MIS_DIRA: "",
    TZIYUNRITZUF: "",
    HEAROTRITZUF: "",
    TZIYUNKNISA: "",
    HEAROTKNISA: "",
    TZIYUNITUM: "",
    HEAROTITUM: "",
    TZIYUNSORAGIM: "",
    HEAROTSORAGIM: "",
    TZIYUNHASHMAL: "",
    HEAROTHASHMAL: "",
    TZIYUNNEZILOT: "",
    HEAROTNEZILOT: "",
    TZIYUNPNIM: "",
    HEAROTPNIM: "",
    TZIYUNDLATOT: "",
    HEAROTDLATOT: "",
    TZIYUNCHALONOT: "",
    HEAROTCHALONOT: "",
    TZIYUNTRISIM: "",
    HEAROTTRISIM: "",
    TZIYUNMITBACH: "",
    HEAROTMITBACH: "",
    TZIYUNSHERUTIM: "",
    HEAROTSHERUTIM: "",
    TZIYUNMIKLACHAT: "",
    HEAROTMIKLACHAT: "",
    TZIYUNKLALI: "",
    HEAROTKLALI: "",
    TZIYUNPCHAT: "",
    HEAROTPCHAT: "",
    TZIYUNBNIYA: "",
    HEAROTBNIYA: "",
    TZIYUNCHIMUM: "",
    HEAROTCHIMUM: "",
    TZIYUNASBEST: "",
    HEAROTASBEST: "",
    TZIYUNGALAY: "",
    HEAROTGALAY: "",
    SHEMPRATI: "רחל",
    SHEMMISHPACHA: "אלישע",
    RECHOV: "חרמון",
    BAIT: "9",
    ISHUV: "יבנה",
    MIKUD: "8159112",
    MISPARCESHBON: "42681",
    EMGVIYA: "הוראת קבע",
    MATZAVICHLUS: "שכירות",
    TARICHLUS: "1996-02-23 00:00:00.0",
    TARBIKURACHARON: "2022-11-27 00:00:00.0",
    MISNEFASHOT: "1",
    YELADIMAD21: "0",
    TELNAYAD: "0584354812",
    TELDIRA: "",
    TELAVODA: "",
    DOARELECTRONI: "",
    TITLENOSAF: "בן/בת",
    TELNOSAF: "0532279617",
    TITLENOSAF2: "",
    TELNOSAF2: "",
    TELHEAROT: "",
    DRZIHUY: "023607377",
    DRPRATI: "רחל",
    DRMISHPACHA: "אלישע",
    DRSEX: "2",
    DRTARLEDA: "1968-03-29 00:00:00.0",
    DRMATZAV: "4",
    BZZIHUY: "",
    BZPRATI: "",
    BZMISHPACHA: "",
    BZSEX: "",
    BZTARLEDA: "",
    BZMATZAV: "",
    NISMACHIM: "",
    TZIHUY: "023607377",
    HEAROT: "",
    SCHDNETO: "695.32",
    SCHDBRUTO: "955.37",
    SUGSCHD: "מסובסד",
    SUGHANACH: "מידרוג ארצי",
    TARSIYUM: "2019-11-30 00:00:00.0",
    CHOVTVIAA: "",
    KOMA: "04",
    ITRATCHOV: "0",
    CHOV: "0",
    STATUSCHOZE: "1",
    ISEXISTSBIKUR: "1",
    ISTAZHIRDAYAR: "0",
    ISGARBEGAPO: "1",
    ISBIKURKASHISH: "0",
    ISTAMA: "0",
    ISTAZHIRDAYARBZ: "0",
    ISTROMI: "1",
    ISSCHIRM: "0",
  },
];

export const tenant_2 = [
  {
    CHIMUMMAYIM: "דוד שמש דירתי",
    CHADARBITACHON: "מקלט אזורי",
    SHETACH: "64",
    CHADARIM: "2",
    CATZAEICHADARIM: "1",
    MADREGOT: "4",
    TAR_BIKUR: "",
    MIS_DIRA: "",
    TZIYUNRITZUF: "",
    HEAROTRITZUF: "",
    TZIYUNKNISA: "",
    HEAROTKNISA: "",
    TZIYUNITUM: "",
    HEAROTITUM: "",
    TZIYUNSORAGIM: "",
    HEAROTSORAGIM: "",
    TZIYUNHASHMAL: "",
    HEAROTHASHMAL: "",
    TZIYUNNEZILOT: "",
    HEAROTNEZILOT: "",
    TZIYUNPNIM: "",
    HEAROTPNIM: "",
    TZIYUNDLATOT: "",
    HEAROTDLATOT: "",
    TZIYUNCHALONOT: "",
    HEAROTCHALONOT: "",
    TZIYUNTRISIM: "",
    HEAROTTRISIM: "",
    TZIYUNMITBACH: "",
    HEAROTMITBACH: "",
    TZIYUNSHERUTIM: "",
    HEAROTSHERUTIM: "",
    TZIYUNMIKLACHAT: "",
    HEAROTMIKLACHAT: "",
    TZIYUNKLALI: "",
    HEAROTKLALI: "",
    TZIYUNPCHAT: "",
    HEAROTPCHAT: "",
    TZIYUNBNIYA: "",
    HEAROTBNIYA: "",
    TZIYUNCHIMUM: "",
    HEAROTCHIMUM: "",
    TZIYUNASBEST: "",
    HEAROTASBEST: "",
    TZIYUNGALAY: "",
    HEAROTGALAY: "",
    SHEMPRATI: "אננה",
    SHEMMISHPACHA: "תמיר",
    RECHOV: "שד קוגל",
    BAIT: "20",
    ISHUV: "חולון",
    MIKUD: "5825406",
    MISPARCESHBON: "55888",
    EMGVIYA: "הוראת קבע",
    MATZAVICHLUS: "שכירות",
    TARICHLUS: "1992-03-01 00:00:00.0",
    TARBIKURACHARON: "2022-08-03 00:00:00.0",
    MISNEFASHOT: "1",
    YELADIMAD21: "0",
    TELNAYAD: "0528929536",
    TELDIRA: "",
    TELAVODA: "",
    DOARELECTRONI: "",
    TITLENOSAF: "סוזנה ב",
    TELNOSAF: "0543241672",
    TITLENOSAF2: "",
    TELNOSAF2: "",
    TELHEAROT: "",
    DRZIHUY: "017291923",
    DRPRATI: "אננה",
    DRMISHPACHA: "תמיר",
    DRSEX: "2",
    DRTARLEDA: "1950-11-17 00:00:00.0",
    DRMATZAV: "2",
    BZZIHUY: "",
    BZPRATI: "",
    BZMISHPACHA: "",
    BZSEX: "",
    BZTARLEDA: "",
    BZMATZAV: "",
    NISMACHIM: "",
    TZIHUY: "017291923",
    HEAROT: "",
    SCHDNETO: "239.57",
    SCHDBRUTO: "2480.23",
    SUGSCHD: 'שד"ח',
    SUGHANACH: "מידרוג ארצי - מינימום",
    TARSIYUM: "2022-11-30 00:00:00.0",
    CHOVTVIAA: "",
    KOMA: "01",
    ITRATCHOV: "0",
    CHOV: "0",
    STATUSCHOZE: "1",
    ISEXISTSBIKUR: "1",
    ISTAZHIRDAYAR: "0",
    ISGARBEGAPO: "1",
    ISBIKURKASHISH: "0",
    ISTAMA: "0",
    ISTAZHIRDAYARBZ: "0",
    ISTROMI: "0",
    ISSCHIRM: "0",
  },
];

export const tenant_3 = [
  {
    CHIMUMMAYIM: "דוד שמש דירתי",
    CHADARBITACHON: "מקלט אזורי",
    SHETACH: "76",
    CHADARIM: "3",
    CATZAEICHADARIM: "1",
    MADREGOT: "4",
    TAR_BIKUR: "",
    MIS_DIRA: "",
    TZIYUNRITZUF: "",
    HEAROTRITZUF: "",
    TZIYUNKNISA: "",
    HEAROTKNISA: "",
    TZIYUNITUM: "",
    HEAROTITUM: "",
    TZIYUNSORAGIM: "",
    HEAROTSORAGIM: "",
    TZIYUNHASHMAL: "",
    HEAROTHASHMAL: "",
    TZIYUNNEZILOT: "",
    HEAROTNEZILOT: "",
    TZIYUNPNIM: "",
    HEAROTPNIM: "",
    TZIYUNDLATOT: "",
    HEAROTDLATOT: "",
    TZIYUNCHALONOT: "",
    HEAROTCHALONOT: "",
    TZIYUNTRISIM: "",
    HEAROTTRISIM: "",
    TZIYUNMITBACH: "",
    HEAROTMITBACH: "",
    TZIYUNSHERUTIM: "",
    HEAROTSHERUTIM: "",
    TZIYUNMIKLACHAT: "",
    HEAROTMIKLACHAT: "",
    TZIYUNKLALI: "",
    HEAROTKLALI: "",
    TZIYUNPCHAT: "",
    HEAROTPCHAT: "",
    TZIYUNBNIYA: "",
    HEAROTBNIYA: "",
    TZIYUNCHIMUM: "",
    HEAROTCHIMUM: "",
    TZIYUNASBEST: "",
    HEAROTASBEST: "",
    TZIYUNGALAY: "",
    HEAROTGALAY: "",
    SHEMPRATI: "חיים",
    SHEMMISHPACHA: "כהן",
    RECHOV: "הכנסת",
    BAIT: "2",
    ISHUV: "חולון",
    MIKUD: "5882051",
    MISPARCESHBON: "55804",
    EMGVIYA: "הוראת קבע",
    MATZAVICHLUS: "שכירות",
    TARICHLUS: "1988-09-01 00:00:00.0",
    TARBIKURACHARON: "2022-08-03 00:00:00.0",
    MISNEFASHOT: "4",
    YELADIMAD21: "0",
    TELNAYAD: "0502472229",
    TELDIRA: "",
    TELAVODA: "",
    DOARELECTRONI: "",
    TITLENOSAF: "שכן/ה",
    TELNOSAF: "0528333061",
    TITLENOSAF2: "",
    TELNOSAF2: "",
    TELHEAROT: "",
    DRZIHUY: "054210588",
    DRPRATI: "חיים",
    DRMISHPACHA: "כהן",
    DRSEX: "1",
    DRTARLEDA: "1957-09-03 00:00:00.0",
    DRMATZAV: "1",
    BZZIHUY: "057847725",
    BZPRATI: "רחל",
    BZMISHPACHA: "כהן",
    BZSEX: "2",
    BZTARLEDA: "1962-05-28 00:00:00.0",
    BZMATZAV: "1",
    NISMACHIM:
      "021798228$ ברוך$ כהן$ 01-אוגוסט -1983$ 2$ 5$ 75$ 01-אוגוסט -2001$ $ $ & 034587196$ עזרא$ כהן$ 02-יולי   -1985$ 2$ 5$ $ $ $ $ ",
    TZIHUY: "054210588",
    HEAROT: "שכן - וועד הבנין רונן",
    SCHDNETO: "873.34",
    SCHDBRUTO: "1455.57",
    SUGSCHD: "מסובסד",
    SUGHANACH: "מידרוג ארצי",
    TARSIYUM: "2023-11-30 00:00:00.0",
    CHOVTVIAA: "",
    KOMA: "01",
    ITRATCHOV: "0",
    CHOV: "0",
    STATUSCHOZE: "1",
    ISEXISTSBIKUR: "1",
    ISTAZHIRDAYAR: "0",
    ISGARBEGAPO: "0",
    ISBIKURKASHISH: "0",
    ISTAMA: "0",
    ISTAZHIRDAYARBZ: "0",
    ISTROMI: "0",
    ISSCHIRM: "0",
  },
];

export const tableDate = [
  {
    key: "collectionMeans",
    value: [
      {
        TABLENAME: "EMGVIA",
        FILTER1: "",
        FIELD1: "01",
        FIELD2: "הוראת קבע",
      },
      {
        TABLENAME: "EMGVIA",
        FILTER1: "",
        FIELD1: "02",
        FIELD2: "ניכוי בשכר",
      },
      {
        TABLENAME: "EMGVIA",
        FILTER1: "",
        FIELD1: "03",
        FIELD2: "שובר",
      },
      {
        TABLENAME: "EMGVIA",
        FILTER1: "",
        FIELD1: "04",
        FIELD2: "הודעת חיוב",
      },
      {
        TABLENAME: "EMGVIA",
        FILTER1: "",
        FIELD1: "05",
        FIELD2: "שיקים דחויים",
      },
      {
        TABLENAME: "EMGVIA",
        FILTER1: "",
        FIELD1: "06",
        FIELD2: "שיקים",
      },
      {
        TABLENAME: "EMGVIA",
        FILTER1: "",
        FIELD1: "07",
        FIELD2: "ממסר",
      },
      {
        TABLENAME: "EMGVIA",
        FILTER1: "",
        FIELD1: "08",
        FIELD2: "קיזוז עם ארנונה",
      },
    ],
  },
  {
    key: "securityRoom",
    value: [
      {
        TABLENAME: "BITACHON",
        FILTER1: "",
        FIELD1: "1",
        FIELD2: "חדר בטחוני",
      },
      {
        TABLENAME: "BITACHON",
        FILTER1: "",
        FIELD1: "2",
        FIELD2: "תוספת",
      },
      {
        TABLENAME: "BITACHON",
        FILTER1: "",
        FIELD1: "3",
        FIELD2: 'ממ"ד',
      },
      {
        TABLENAME: "BITACHON",
        FILTER1: "",
        FIELD1: "4",
        FIELD2: 'ממ"ק',
      },
      {
        TABLENAME: "BITACHON",
        FILTER1: "",
        FIELD1: "5",
        FIELD2: "מקלט עילי לבניין",
      },
      {
        TABLENAME: "BITACHON",
        FILTER1: "",
        FIELD1: "6",
        FIELD2: "מקלט תת קרקעי לבניין",
      },
      {
        TABLENAME: "BITACHON",
        FILTER1: "",
        FIELD1: "7",
        FIELD2: "מקלט אזורי",
      },
      {
        TABLENAME: "BITACHON",
        FILTER1: "",
        FIELD1: "8",
        FIELD2: "מחסה בלבד - לא תקני",
      },
    ],
  },
  {
    key: "waterHeating",
    value: [
      {
        TABLENAME: "CHIMUM",
        FILTER1: "",
        FIELD1: "00",
        FIELD2: "חימום על גז",
      },
      {
        TABLENAME: "CHIMUM",
        FILTER1: "",
        FIELD1: "01",
        FIELD2: "הסקה מרכזית",
      },
      {
        TABLENAME: "CHIMUM",
        FILTER1: "",
        FIELD1: "02",
        FIELD2: "דוד שמש מרכזי",
      },
      {
        TABLENAME: "CHIMUM",
        FILTER1: "",
        FIELD1: "03",
        FIELD2: "דוד שמש דירתי",
      },
      {
        TABLENAME: "CHIMUM",
        FILTER1: "",
        FIELD1: "04",
        FIELD2: "דוד חשמל",
      },
      {
        TABLENAME: "CHIMUM",
        FILTER1: "",
        FIELD1: "05",
        FIELD2: "מכשיר אטמור",
      },
      {
        TABLENAME: "CHIMUM",
        FILTER1: "",
        FIELD1: "06",
        FIELD2: "הסקה מרכזית ודוד חשמל",
      },
      {
        TABLENAME: "CHIMUM",
        FILTER1: "",
        FIELD1: "07",
        FIELD2: "לא ניתן להתקין דוד שמש (סופית)",
      },
      {
        TABLENAME: "CHIMUM",
        FILTER1: "",
        FIELD1: "08",
        FIELD2: "לא ניתן להתקין דוד שמש (זמנית)",
      },
      {
        TABLENAME: "CHIMUM",
        FILTER1: "",
        FIELD1: "09",
        FIELD2: "הסקה מרכזית ודוד שמש",
      },
    ],
  },
  {
    key: "actualUse",
    value: [
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "01",
        FIELD2: "מגורים",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "02",
        FIELD2: "חנות /לרבות קיוסק/",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "03",
        FIELD2: "בית מלאכה /סדנה/מוסך/",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "05",
        FIELD2: "משרד",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "06",
        FIELD2: "מחסן",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "09",
        FIELD2: "משרד בבעלות עמידר",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "13",
        FIELD2: "בית כנסת",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "14",
        FIELD2: 'מוסד חנוכי שאינו גן,בי"ס,ישיבה',
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "16",
        FIELD2: "מקווה",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "18",
        FIELD2: "מועדון",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "21",
        FIELD2: 'מוסד רפואה  /כולל קופ"ח ובי"ח',
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "24",
        FIELD2: "גן ילדים",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "32",
        FIELD2: "אם בית",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "33",
        FIELD2: "דירות סטודנטים",
      },
      {
        TABLENAME: "SHIMUSH",
        FILTER1: "",
        FIELD1: "34",
        FIELD2: "קיבוץ עירוני",
      },
    ],
  },
  {
    key: "mobile",
    value: [
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "02",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "03",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "04",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "050",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "051",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "052",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "053",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "054",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "055",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "056",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "057",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "058",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "059",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "072",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "073",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "074",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "076",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "077",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "078",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "08",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "09",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "153",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "159",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "170",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "180",
        FIELD2: "",
      },
      {
        TABLENAME: "KIDOMET",
        FILTER1: "",
        FIELD1: "190",
        FIELD2: "",
      },
    ],
  },
  {
    key: "streets",
    value: [],
  },
];
